version: '3.8'

services:
  backend:
    build: .
    image: themagicai
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/themagicai_image
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    container_name: postgres_db

volumes:
  postgres_data:
