# Generated by Django 4.1.7 on 2023-02-27 18:59

from django.db import migrations, models
import themagicai.users.manager


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", themagicai.users.manager.CustomUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Email of User"
            ),
        ),
    ]
