# Generated by Django 4.1.7 on 2023-02-22 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name="letter",
            old_name="body",
            new_name="about",
        ),
        migrations.RenameField(
            model_name="postcv",
            old_name="body",
            new_name="about",
        ),
        migrations.AddField(
            model_name="letter",
            name="company",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="letter",
            name="position",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="letter",
            name="requirement",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="letter",
            name="result",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="letter",
            name="skills",
            field=models.ManyToManyField(to="app.skill"),
        ),
        migrations.AddField(
            model_name="postcv",
            name="company",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="postcv",
            name="position",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="postcv",
            name="requirement",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="postcv",
            name="result",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="postcv",
            name="skills",
            field=models.ManyToManyField(to="app.skill"),
        ),
        migrations.AddField(
            model_name="letter",
            name="grade",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="app.grade"
            ),
        ),
        migrations.AddField(
            model_name="postcv",
            name="grade",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="app.grade"
            ),
        ),
    ]
