# Generated by Django 4.1.7 on 2023-02-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_grade_rename_body_letter_about_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="letter",
            name="skills",
            field=models.ManyToManyField(blank=True, to="app.skill"),
        ),
        migrations.AlterField(
            model_name="postcv",
            name="skills",
            field=models.ManyToManyField(blank=True, to="app.skill"),
        ),
    ]
