# Generated by Django 4.1.7 on 2023-02-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_skill_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="letter",
            name="grade",
        ),
        migrations.RemoveField(
            model_name="postcv",
            name="grade",
        ),
        migrations.AlterField(
            model_name="letter",
            name="skills",
            field=models.ManyToManyField(to="app.skill"),
        ),
        migrations.AlterField(
            model_name="postcv",
            name="skills",
            field=models.ManyToManyField(to="app.skill"),
        ),
    ]
